/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'

export function FoodSpace(props) {
  const { animation , section } = props;

  const groupRef = useRef()
  const { nodes, materials } = useGLTF('/foodSpace.glb')

  const rotationSpeed = 0.5;
  const baseScaleSpeed = 0; // Base scale speed when section is not 7
  const specialScaleSpeed = 0; // Scale speed when section is 7
  // Use the useFrame hook to update the rotation of each group
  useFrame((_, delta) => {
   
    // Iterate over each child of the group and update its rotation
    groupRef.current.children.forEach(child => {
      // Calculate the new rotation angle based on speed and delta time
      const newRotation = child.rotation.clone()
      newRotation.y += rotationSpeed * delta
      newRotation.y %= Math.PI * 2 // Keep rotation within 0 to 2*PI

      const scaleSpeed = section === 6 ? specialScaleSpeed : baseScaleSpeed;

      const newScale = child.scale.clone();
      newScale.x += scaleSpeed * delta;
      newScale.y += scaleSpeed * delta;
      newScale.z += scaleSpeed * delta;

      // Set the new rotation and scale
      child.rotation.copy(newRotation);
      // child.scale.copy(newScale);

    })
  })

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group position={[-2.61, 0.133, -5.626]} rotation={[-Math.PI / 2, 0, 0]} scale={0.16}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[1.243, 6.159, 1.637]} rotation={[Math.PI, -0.655, Math.PI]}>
            <group position={[5.499, 0.31, 3.656]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_7.geometry}
                material={materials.material_0}
                position={[-18.494, -3.601, 14.55]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials['Material.005']}
              position={[-18.494, -3.601, 14.55]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_5.geometry}
              material={materials['Material.006']}
              position={[-18.494, -3.601, 14.55]}
            />
          </group>
        </group>
      </group>
      <group position={[0.075, 1.62, -0.964]} rotation={[-Math.PI / 2, 0, 0]} scale={0.905}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials['Material.001']}
          position={[2.334, 1.34, 1.31]}
          scale={0.489}
        />
      </group>
      <group position={[0.367, -0.055, 0.817]} rotation={[-Math.PI / 2, 0, 0]} scale={0.905}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[135.301, 170.361, 168.76]} scale={[141.901, 145.723, 100]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Plane_Material_0.geometry}
              material={materials['Material.002']}
              position={[-1.033, 1.521, 2.881]}
              scale={0.56}
            />
          </group>
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4001.geometry}
        material={materials['material_0.001']}
        position={[3.802, -1.68, -0.601]}
        scale={1.502}
      />
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2001.geometry}
          material={materials.base_material}
          position={[3.222, -2.475, -3.803]}
          scale={1.167}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.606}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-1.466, -0.023, 0.002]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Mesh_0_Material_0_0.geometry}
              material={materials.Material_0}
              position={[2.88, 2.935, 1.77]}
            />
          </group>
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4003.geometry}
        material={materials['material_0.002']}
        position={[-6.661, 0.14, -3.826]}
        scale={2.149}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4004.geometry}
        material={materials['material_0.003']}
        position={[-0.288, 0.305, 0.721]}
        scale={1.518}
      />
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.126, 224.959, -5.689]} rotation={[-3.133, -1.482, 3.134]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chocolate_1_chocolate_0.geometry}
              material={materials.chocolate}
              position={[-1919.133, 147.365, -90.545]}
            />
          </group>
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.143}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial001.geometry}
            material={materials.defaultMat}
            position={[-16.9, -25.97, -18.275]}
            scale={3.275}
          />
        </group>
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.013}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wipes_huggers_LG_LOD00_baby_items_001_M_0.geometry}
            material={materials.baby_items_001_M}
            position={[170.884, 27.967, 127.215]}
          />
        </group>
      </group>
      <group position={[0.064, 0.2, -0.954]} rotation={[-1.145, 0.315, -3.097]} scale={0.013}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.wipes_huggers_LG_LOD00_baby_items_001_M_0001.geometry}
            material={materials['baby_items_001_M.001']}
            position={[127.721, -32.717, 113.841]}
          />
        </group>
      </group>
      <group position={[0.064, 0.2, -0.954]} rotation={[-1.145, 0.315, -3.097]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-138.345, 0, 0.242]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.819, 0.819, 1]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Can_01_-_Default_0001'].geometry}
              material={materials['01_-_Default.001']}
              position={[161.63, -6.319, 0.079]}
              scale={0.007}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Can_02_-_Default_0001'].geometry}
              material={materials['02_-_Default.001']}
              position={[161.63, -6.319, 0.079]}
              scale={0.007}
            />
          </group>
          <group
            position={[-46.537, 0, 0.242]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.819, 0.819, 1]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Can001_02_-_Default_0001'].geometry}
              material={materials['02_-_Default.001']}
              position={[48.28, -1.102, -0.822]}
              scale={0.007}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Can001_03_-_Default_0001'].geometry}
              material={materials['03_-_Default.001']}
              position={[48.28, -1.102, -0.822]}
              scale={0.007}
            />
          </group>
          <group
            position={[45.133, 0, 0.242]}
            rotation={[-Math.PI / 2, 0, 0.698]}
            scale={[0.819, 0.819, 1]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Can002_02_-_Default_0001'].geometry}
              material={materials['02_-_Default.001']}
              position={[-39.082, 39.564, -3.511]}
              scale={0.007}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Can002_07_-_Default_0001'].geometry}
              material={materials['07_-_Default.001']}
              position={[-39.082, 39.564, -3.511]}
              scale={0.007}
            />
          </group>
          <group
            position={[140.983, 0, 0.242]}
            rotation={[-Math.PI / 2, 0, Math.PI / 4]}
            scale={[0.819, 0.819, 1]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Can003_02_-_Default_0001'].geometry}
              material={materials['02_-_Default.001']}
              position={[-127.235, 123.629, 3.214]}
              scale={0.007}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['Can003_08_-_Default_0001'].geometry}
              material={materials['08_-_Default.001']}
              position={[-127.235, 123.629, 3.214]}
              scale={0.007}
            />
          </group>
        </group>
      </group>
      <group position={[0.064, 0.2, -0.954]} rotation={[-1.145, 0.315, -3.097]} scale={0.143}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial002.geometry}
            material={materials['defaultMat.001']}
            position={[-21.903, -20.803, -34.96]}
            scale={3.575}
          />
        </group>
      </group>
      <group position={[0.064, 0.2, -0.954]} rotation={[-1.145, 0.315, -3.097]} scale={0.001}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.126, 224.959, -5.689]} rotation={[-3.133, -1.482, 3.134]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.chocolate_1_chocolate_0001.geometry}
              material={materials['chocolate.001']}
              position={[-1919.133, 147.365, -90.545]}
            />
          </group>
        </group>
      </group>
      <group position={[0.064, 0.2, -0.954]} rotation={[-1.145, 0.315, -3.097]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4005.geometry}
            material={materials['material_0.005']}
            position={[-0.592, 0.394, 0.922]}
            scale={1.601}
          />
        </group>
      </group>
      <group position={[0.064, 0.2, -0.954]} rotation={[-1.145, 0.315, -3.097]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4006.geometry}
            material={materials['material_0.006']}
            position={[-1.589, 0.906, 0.214]}
            scale={1.993}
          />
        </group>
      </group>
      <group position={[0.064, 0.2, -0.954]} rotation={[-1.145, 0.315, -3.097]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.defaultMaterial003.geometry}
            material={materials['M_Juice.001']}
            position={[2.474, 1.272, -4.728]}
            scale={0.815}
          />
        </group>
      </group>
      <group position={[0.064, 0.2, -0.954]} rotation={[-1.145, 0.315, -3.097]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[4.17, 11.791, -4.306]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Sandwich_Sandwich_0001.geometry}
              material={materials['Sandwich.001']}
              position={[3.152, 1.931, 1.483]}
              scale={2.116}
            />
          </group>
        </group>
      </group>
      <group position={[0.064, 0.2, -0.954]} rotation={[-1.145, 0.315, -3.097]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[6.181, 4.734, -518.465]} scale={[10.436, 4.929, 4.929]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.canastas_canasta_0001.geometry}
              material={materials['canasta.001']}
              position={[-47.214, -16.153, 60.471]}
              scale={1.976}
            />
          </group>
          <group
            position={[20.091, 2.023, -513.297]}
            rotation={[-1.052, 0.03, 0.115]}
            scale={6.224}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.carne_carne_0001.geometry}
              material={materials['carne.001']}
              position={[-94.539, -101.349, 59.842]}
              scale={[2.336, 5.333, 3.39]}
            />
          </group>
          <group
            position={[-15.321, 6.124, -527.063]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={2.036}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.frutas_frutas_0001.geometry}
              material={materials['frutas.001']}
              position={[163.152, -178.767, -1.986]}
              scale={3.203}
            />
          </group>
        </group>
      </group>
      <group position={[0.064, 0.2, -0.954]} rotation={[-1.145, 0.315, -3.097]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[91.683, -34.54, 218.327]} scale={[141.901, 145.723, 100]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Plane_Material_0002.geometry}
              material={materials['Material.004']}
              position={[-0.238, -3.683, 2.19]}
              scale={0.478}
            />
          </group>
        </group>
      </group>
      <group position={[0.064, 0.2, -0.954]} rotation={[-1.145, 0.315, -3.097]} scale={0.606}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-1.466, -0.023, 0.002]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Mesh_0_Material_0_0001.geometry}
              material={materials['Material_0.001']}
              position={[-5.29, 0.434, 3.202]}
              scale={[1.084, 1.115, 1.665]}
            />
          </group>
        </group>
      </group>
      <group position={[0.064, 0.2, -0.954]} rotation={[-1.145, 0.315, -3.097]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2002.geometry}
          material={materials['base_material.001']}
          position={[1.579, 1.697, -2.78]}
          scale={1.167}
        />
      </group>
      <group position={[0.064, 0.2, -0.954]} rotation={[-1.145, 0.315, -3.097]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_4008.geometry}
            material={materials['material_0.007']}
            position={[3.802, -1.68, -0.601]}
            scale={1.502}
          />
        </group>
      </group>
      <group position={[-0.337, 0.596, -1.652]} rotation={[-1.145, 0.315, -3.097]} scale={0.905}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[135.301, 170.361, 168.76]} scale={[141.901, 145.723, 100]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Plane_Material_0003.geometry}
              material={materials['Material.007']}
              position={[-1.033, 1.521, 2.881]}
              scale={0.56}
            />
          </group>
        </group>
      </group>
      <group position={[0.535, 1.213, 0.566]} rotation={[-1.145, 0.315, -3.097]} scale={0.905}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2003.geometry}
          material={materials['Material.010']}
          position={[2.334, 1.34, 1.31]}
          scale={0.489}
        />
      </group>
      <group position={[2.82, -2.765, 3.748]} rotation={[-1.145, 0.315, -3.097]} scale={0.16}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[1.243, 6.159, 1.637]} rotation={[Math.PI, -0.655, Math.PI]}>
            <group position={[5.499, 0.31, 3.656]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_7002.geometry}
                material={materials['material_0.004']}
                position={[-18.494, -3.601, 14.55]}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4009.geometry}
              material={materials['Material.009']}
              position={[-18.494, -3.601, 14.55]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_5003.geometry}
              material={materials['Material.008']}
              position={[-18.494, -3.601, 14.55]}
            />
          </group>
        </group>
      </group>
      <group scale={0.01}>
        <group position={[91.683, -34.54, 218.327]} scale={[141.901, 145.723, 100]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane_Material_0001.geometry}
            material={materials['Material.003']}
            position={[-0.238, -3.683, 2.19]}
            scale={0.478}
          />
        </group>
      </group>
      <group scale={0.01}>
        <group position={[6.181, 4.734, -518.465]} scale={[10.436, 4.929, 4.929]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.canastas_canasta_0.geometry}
            material={materials.canasta}
            position={[-47.214, -16.153, 60.471]}
            rotation={[0.238, -0.178, 0.201]}
            scale={1.976}
          />
        </group>
        <group position={[20.091, 2.023, -513.298]} rotation={[-1.052, 0.03, 0.115]} scale={6.224}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.carne_carne_0.geometry}
            material={materials.carne}
            position={[-94.539, -101.349, 59.842]}
            rotation={[0.289, -0.375, -0.014]}
            scale={[2.336, 5.333, 3.39]}
          />
        </group>
        <group
          position={[-15.321, 6.124, -527.063]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={2.036}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.frutas_frutas_0.geometry}
            material={materials.frutas}
            position={[163.152, -178.767, -1.986]}
            scale={3.203}
          />
        </group>
      </group>
      <group scale={0.01}>
        <group position={[4.17, 11.791, -4.306]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sandwich_Sandwich_0.geometry}
            material={materials.Sandwich}
            position={[3.152, 1.931, 1.483]}
            scale={2.116}
          />
        </group>
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial.geometry}
        material={materials.M_Juice}
        position={[2.474, 1.272, -4.728]}
        scale={0.815}
      />
      <group
        position={[-138.345, 0, 0.242]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.819, 0.819, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Can_01_-_Default_0'].geometry}
          material={materials['01_-_Default']}
          position={[161.63, -6.319, 0.079]}
          rotation={[-0.655, 0.413, 0.563]}
          scale={0.007}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Can_02_-_Default_0'].geometry}
          material={materials['02_-_Default']}
          position={[161.63, -6.319, 0.079]}
          rotation={[-0.655, 0.413, 0.563]}
          scale={0.007}
        />
      </group>
      <group
        position={[-46.537, 0, 0.242]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.819, 0.819, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Can001_02_-_Default_0'].geometry}
          material={materials['02_-_Default']}
          position={[48.28, -1.102, -0.822]}
          rotation={[0, 0.382, -0.479]}
          scale={0.007}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Can001_03_-_Default_0'].geometry}
          material={materials['03_-_Default']}
          position={[48.28, -1.102, -0.822]}
          rotation={[0, 0.382, -0.479]}
          scale={0.007}
        />
      </group>
      <group
        position={[45.133, 0, 0.242]}
        rotation={[-Math.PI / 2, 0, 0.698]}
        scale={[0.819, 0.819, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Can002_02_-_Default_0'].geometry}
          material={materials['02_-_Default']}
          position={[-39.082, 39.564, -3.511]}
          scale={0.007}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Can002_07_-_Default_0'].geometry}
          material={materials['07_-_Default']}
          position={[-39.082, 39.564, -3.511]}
          scale={0.007}
        />
      </group>
      <group
        position={[140.983, 0, 0.242]}
        rotation={[-Math.PI / 2, 0, Math.PI / 4]}
        scale={[0.819, 0.819, 1]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Can003_02_-_Default_0'].geometry}
          material={materials['02_-_Default']}
          position={[-127.235, 123.629, 3.214]}
          rotation={[0.192, -0.251, -0.182]}
          scale={0.007}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Can003_08_-_Default_0'].geometry}
          material={materials['08_-_Default']}
          position={[-127.235, 123.629, 3.214]}
          rotation={[0.192, -0.251, -0.182]}
          scale={0.007}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/foodSpace.glb')