/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/


import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Ipad(props) {
  const { nodes, materials } = useGLTF('deviceMoled.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.moble.geometry}
        material={materials['Material.001']}
        // position={[-0.036, -0.05, -0.087]}
        scale={24.162}
      />
    </group> 
  )
}

useGLTF.preload('models/deviceMoled.glb')
